implementing global exception handling
G-Mart-Online/gmart-api pull request #21
Opened 2024-10-08 10:33 UTC by salinda-yasas-99

2024-10-08 10:49 UTC, nimeshnuwanga requested changes

2024-10-08 10:49 UTC, nimeshnuwanga commented on src/main/java/com/gmart/gmart_api/service/UserService.java
> +           // throw new AppException("Login already exists", HttpStatus.BAD_REQUEST);
remove unnecessary comments

2024-10-08 10:49 UTC, nimeshnuwanga commented on src/main/java/com/gmart/gmart_api/exceptions/GlobalExceptionHandler.java
> +    //log in exceptions
Is this comment needed?

2024-10-08 10:49 UTC, nimeshnuwanga commented on src/main/java/com/gmart/gmart_api/exceptions/GlobalExceptionHandler.java
> +    // Global exception handler for any other exceptions
remove unnecessary comments

2024-10-08 10:49 UTC, nimeshnuwanga commented on src/main/java/com/gmart/gmart_api/exceptions/CustomException.java
> +    // You can also add a static factory method to build the CustomException with formatted timestamp
Please remove comments if you are directly copying from the ChatGPT.

2024-10-08 10:49 UTC, nimeshnuwanga commented on src/main/java/com/gmart/gmart_api/exceptions/CustomException.java
> +//
remove unnecessary comments

2024-10-08 10:49 UTC, nimeshnuwanga commented on src/main/java/com/gmart/gmart_api/controller/UserController.java
> +
Remove unnecessary empty lines

2024-10-08 17:24 UTC, salinda-yasas-99 commented on src/main/java/com/gmart/gmart_api/exceptions/GlobalExceptionHandler.java
> +    // Global exception handler for any other exceptions
this comment needed

2024-10-08 17:26 UTC, lakshankd commented on src/main/java/com/gmart/gmart_api/service/UserService.java
>      //delete user by Id
remove this comment as well

2024-10-08 17:26 UTC, lakshankd commented on src/main/java/com/gmart/gmart_api/exceptions/GlobalExceptionHandler.java
> +
remove these unnecessary lines

2024-10-08 17:26 UTC, lakshankd commented on src/main/java/com/gmart/gmart_api/exceptions/CustomException.java
> +//}
Remove these commented code lines

2024-10-08 17:34 UTC, lakshankd approved these changes

2024-10-09 17:30 UTC, nimeshnuwanga approved these changes

2024-10-09 17:30 UTC, merged